apiVersion: apps/v1
kind: Deployment
metadata:
  name: env
spec:
  selector:
    matchLabels:
      pod: both

  replicas: 1
  template:
    metadata:
      labels:
        pod: both

    spec:
      containers:
      - name: prometheus 
        image: prom/prometheus

        ports:
        - containerPort: 9090

        volumeMounts:
          - name: prom-vol
            mountPath: /data/


      - name: grafana
        image: grafana/grafana

        ports:
        - containerPort: 3000

        volumeMounts:
          - name: graf-vol
            mountPath: /var/lib/grafana/

      volumes:
      - name: prom-vol
        persistentVolumeClaim:
          claimName: prometheus-pvc

      - name: graf-vol
        persistentVolumeClaim:
          claimName: grafana-pvc 