apiVersion: v1
kind: Service
metadata:
  name: svc
spec:
  type: NodePort
  selector:
    pod: both

  ports:
  - port: 9090
    protocol: TCP
    name: prom-port
  - port: 3000
    protocol: TCP
    name: graf-port